# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32d0695f4a9a7b2304d7b17f3b8133aaef2253b310148a3b82a35e9fcecb8761a1e95c9d851fd3ad83cf0e25989badd1a32e151e9f990b32855a406d42744942

test:
  secret_key_base: d06438c6f3b4f999db94ecc3d226f625fdd5e66d79adadd7336f693970659d06801d3706b718ee7d90926cbee29131da89c06b122b1f58856d71ed5893692b69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
